<a href="https://colab.research.google.com/github/Faouzi-Slimi/python_Avancee/blob/main/Next_Words_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd 
import numpy as np
from PIL import Image
import os
import cv2
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical
from keras import layers,Sequential
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.preprocessing.text import Tokenizer
from sklearn import preprocessing

import time
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
from numpy import array
import pandas as pd
import numpy as np
import seaborn as sns
import glob
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from keras.preprocessing.text import Tokenizer
from keras.preprocessing import sequence
from tensorflow.keras import layers
from keras.layers import Embedding
from tensorflow.keras.layers import LSTM,Bidirectional,GRU

from tensorflow.keras.layers import Dense
from tensorflow.keras import optimizers

In [ ]:
data="""Artificial Intelligence (AI) is a technical science that studies and develops theories, methods, technologies, and applications for simulating and extending human intelligence. The purpose of AI is to enable machines to think like
people and to make machines intelligent. Today, AI has become an interdisciplinary course that involves various fields."""

In [ ]:
tokenizer = Tokenizer()
words=tokenizer.fit_on_texts([data])

In [ ]:
sequence_data = tokenizer.texts_to_sequences([data])[0]


[8,
 4,
 2,
 5,
 9,
 10,
 11,
 6,
 12,
 1,
 13,
 14,
 15,
 16,
 1,
 17,
 18,
 19,
 1,
 20,
 21,
 4,
 22,
 23,
 24,
 2,
 5,
 3,
 25,
 7,
 3,
 26,
 27,
 28,
 1,
 3,
 29,
 7,
 30,
 31,
 2,
 32,
 33,
 34,
 35,
 36,
 6,
 37,
 38,
 39]

In [ ]:
len(sequence_data)

50

In [ ]:
sequence_data

[8,
 4,
 2,
 5,
 9,
 10,
 11,
 6,
 12,
 1,
 13,
 14,
 15,
 16,
 1,
 17,
 18,
 19,
 1,
 20,
 21,
 4,
 22,
 23,
 24,
 2,
 5,
 3,
 25,
 7,
 3,
 26,
 27,
 28,
 1,
 3,
 29,
 7,
 30,
 31,
 2,
 32,
 33,
 34,
 35,
 36,
 6,
 37,
 38,
 39]

In [ ]:
X= []

for i in range(len(sequence_data)-1):
    words=sequence_data[i]
    X.append(words)
    
    
X= np.array(X)

In [ ]:
X.shape

(49,)

In [ ]:
X

array([ 8,  4,  2,  5,  9, 10, 11,  6, 12,  1, 13, 14, 15, 16,  1, 17, 18,
       19,  1, 20, 21,  4, 22, 23, 24,  2,  5,  3, 25,  7,  3, 26, 27, 28,
        1,  3, 29,  7, 30, 31,  2, 32, 33, 34, 35, 36,  6, 37, 38])

In [ ]:
X

array([ 8,  4,  2,  5,  9, 10, 11,  6, 12,  1, 13, 14, 15, 16,  1, 17, 18,
       19,  1, 20, 21,  4, 22, 23, 24,  2,  5,  3, 25,  7,  3, 26, 27, 28,
        1,  3, 29,  7, 30, 31,  2, 32, 33, 34, 35, 36,  6, 37, 38])

In [ ]:
Y= []

for i in range(1,len(sequence_data)):
    words=sequence_data[i]
    Y.append(words)
    
    
Y = np.array(Y)


In [ ]:
Y.shape

(49,)

In [ ]:
Y

array([ 4,  2,  5,  9, 10, 11,  6, 12,  1, 13, 14, 15, 16,  1, 17, 18, 19,
        1, 20, 21,  4, 22, 23, 24,  2,  5,  3, 25,  7,  3, 26, 27, 28,  1,
        3, 29,  7, 30, 31,  2, 32, 33, 34, 35, 36,  6, 37, 38, 39])

In [ ]:
vocab_size = len(tokenizer.word_index) + 1

In [ ]:
tokenizer.word_index

{'and': 1,
 'ai': 2,
 'to': 3,
 'intelligence': 4,
 'is': 5,
 'that': 6,
 'machines': 7,
 'artificial': 8,
 'a': 9,
 'technical': 10,
 'science': 11,
 'studies': 12,
 'develops': 13,
 'theories': 14,
 'methods': 15,
 'technologies': 16,
 'applications': 17,
 'for': 18,
 'simulating': 19,
 'extending': 20,
 'human': 21,
 'the': 22,
 'purpose': 23,
 'of': 24,
 'enable': 25,
 'think': 26,
 'like': 27,
 'people': 28,
 'make': 29,
 'intelligent': 30,
 'today': 31,
 'has': 32,
 'become': 33,
 'an': 34,
 'interdisciplinary': 35,
 'course': 36,
 'involves': 37,
 'various': 38,
 'fields': 39}

In [ ]:
vocab_size

40

In [ ]:
model = Sequential()
model.add(Embedding(vocab_size,40, input_length=1))
model.add(LSTM(1000, return_sequences=True))
model.add(LSTM(1000))
model.add(Dense(1000, activation="relu"))
model.add(Dense(vocab_size, activation="softmax"))

In [ ]:
Y = to_categorical(Y, num_classes=vocab_size)

In [ ]:
model.compile(loss="categorical_crossentropy", optimizer='adam',metrics=['accuracy'])
model.fit(X, Y, epochs=100)

Epoch 1/100
2/2 [==============================] - 5s 124ms/step - loss: 3.6895 - accuracy: 0.0408
Epoch 2/100
2/2 [==============================] - 0s 120ms/step - loss: 3.6854 - accuracy: 0.0816
Epoch 3/100
2/2 [==============================] - 0s 132ms/step - loss: 3.6802 - accuracy: 0.0816
Epoch 4/100
2/2 [==============================] - 0s 118ms/step - loss: 3.6747 - accuracy: 0.0816
Epoch 5/100
2/2 [==============================] - 0s 120ms/step - loss: 3.6666 - accuracy: 0.0816
Epoch 6/100
2/2 [==============================] - 0s 120ms/step - loss: 3.6544 - accuracy: 0.0816
Epoch 7/100
2/2 [==============================] - 0s 124ms/step - loss: 3.6370 - accuracy: 0.0816
Epoch 8/100
2/2 [==============================] - 0s 125ms/step - loss: 3.6107 - accuracy: 0.0816
Epoch 9/100
2/2 [==============================] - 0s 134ms/step - loss: 3.5751 - accuracy: 0.0816
Epoch 10/100
2/2 [==============================] - 0s 128ms/step - loss: 3.5279 - accuracy: 0.0816
Epoch 11/

In [ ]:
tokenizer.word_index.items()

dict_items([('and', 1), ('ai', 2), ('to', 3), ('intelligence', 4), ('is', 5), ('that', 6), ('machines', 7), ('artificial', 8), ('a', 9), ('technical', 10), ('science', 11), ('studies', 12), ('develops', 13), ('theories', 14), ('methods', 15), ('technologies', 16), ('applications', 17), ('for', 18), ('simulating', 19), ('extending', 20), ('human', 21), ('the', 22), ('purpose', 23), ('of', 24), ('enable', 25), ('think', 26), ('like', 27), ('people', 28), ('make', 29), ('intelligent', 30), ('today', 31), ('has', 32), ('become', 33), ('an', 34), ('interdisciplinary', 35), ('course', 36), ('involves', 37), ('various', 38), ('fields', 39)])

In [ ]:
word=input()
wordval = tokenizer.texts_to_sequences([word])[0]
pred=model.predict(wordval)
pred2=np.argmax(pred)
for key, values in tokenizer.word_index.items():
        if  values == pred2:
            nextword=key
            print(nextword)

technical
science


In [ ]:
wordval

[8]

In [ ]:
pred

array([[1.09345512e-22, 2.87982577e-04, 7.11975929e-07, 1.01182386e-05,
        9.98656392e-01, 3.49365719e-13, 3.12959741e-10, 1.02363294e-03,
        1.01829175e-21, 6.69888004e-06, 8.17006900e-15, 4.54693307e-21,
        1.76197941e-17, 4.41300614e-08, 3.85786516e-17, 1.05010436e-07,
        5.77022888e-07, 1.45365151e-08, 1.44119065e-14, 2.83453470e-19,
        5.08604749e-08, 4.99322653e-07, 1.31793404e-05, 1.43366944e-19,
        2.61358730e-12, 8.12432725e-21, 3.34351858e-19, 6.62308773e-16,
        3.66712508e-19, 1.14596788e-19, 2.82494056e-10, 2.90076938e-11,
        3.29917343e-12, 2.85868789e-17, 6.18327487e-15, 3.39412303e-20,
        3.49210090e-19, 9.66236622e-18, 6.09675427e-15, 2.69059026e-13]],
      dtype=float32)

In [ ]:
pred2

4

In [ ]:
word=input()
wordval = tokenizer.texts_to_sequences([word])[0]
pred=model.predict(wordval)
pred2=np.argmax(pred,axis=1)


artificial


In [ ]:
nextword=tokenizer.sequences_to_texts([pred2])

In [ ]:
nextword

['intelligence']

In [ ]:

model = Sequential()
model.add(Embedding(vocab_size,40, input_length=1))
model.add(Bidirectional(LSTM(1000, return_sequences=True)))
model.add(Bidirectional(1000))
model.add(Dense(1000, activation="relu"))
model.add(Dense(vocab_size, activation="softmax"))

ValueError: ignored